name: Publish Nuget 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.3.1
        
    - name: Publish NuGet
      # You may pin to the exact commit or the version.
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH:  src/SeungyongShim.Akka.Extensions.DependencyInjection
        NUGET_KEY: ${{ secrets.api }}
        VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
        INCLUDE_SYMBOLS: true 
